# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonathan/Personal/library

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonathan/Personal/library

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/Personal/library/CMakeFiles /home/jonathan/Personal/library//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/Personal/library/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stm32h743_baremetal.elf

# Build rule for target.
stm32h743_baremetal.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32h743_baremetal.elf
.PHONY : stm32h743_baremetal.elf

# fast build rule for target.
stm32h743_baremetal.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/build
.PHONY : stm32h743_baremetal.elf/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

drivers/tielve_stm32h743_gpio.obj: drivers/tielve_stm32h743_gpio.c.obj
.PHONY : drivers/tielve_stm32h743_gpio.obj

# target to build an object file
drivers/tielve_stm32h743_gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_gpio.c.obj
.PHONY : drivers/tielve_stm32h743_gpio.c.obj

drivers/tielve_stm32h743_gpio.i: drivers/tielve_stm32h743_gpio.c.i
.PHONY : drivers/tielve_stm32h743_gpio.i

# target to preprocess a source file
drivers/tielve_stm32h743_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_gpio.c.i
.PHONY : drivers/tielve_stm32h743_gpio.c.i

drivers/tielve_stm32h743_gpio.s: drivers/tielve_stm32h743_gpio.c.s
.PHONY : drivers/tielve_stm32h743_gpio.s

# target to generate assembly for a file
drivers/tielve_stm32h743_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_gpio.c.s
.PHONY : drivers/tielve_stm32h743_gpio.c.s

drivers/tielve_stm32h743_spi.obj: drivers/tielve_stm32h743_spi.c.obj
.PHONY : drivers/tielve_stm32h743_spi.obj

# target to build an object file
drivers/tielve_stm32h743_spi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_spi.c.obj
.PHONY : drivers/tielve_stm32h743_spi.c.obj

drivers/tielve_stm32h743_spi.i: drivers/tielve_stm32h743_spi.c.i
.PHONY : drivers/tielve_stm32h743_spi.i

# target to preprocess a source file
drivers/tielve_stm32h743_spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_spi.c.i
.PHONY : drivers/tielve_stm32h743_spi.c.i

drivers/tielve_stm32h743_spi.s: drivers/tielve_stm32h743_spi.c.s
.PHONY : drivers/tielve_stm32h743_spi.s

# target to generate assembly for a file
drivers/tielve_stm32h743_spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_spi.c.s
.PHONY : drivers/tielve_stm32h743_spi.c.s

drivers/tielve_stm32h743_systick.obj: drivers/tielve_stm32h743_systick.c.obj
.PHONY : drivers/tielve_stm32h743_systick.obj

# target to build an object file
drivers/tielve_stm32h743_systick.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_systick.c.obj
.PHONY : drivers/tielve_stm32h743_systick.c.obj

drivers/tielve_stm32h743_systick.i: drivers/tielve_stm32h743_systick.c.i
.PHONY : drivers/tielve_stm32h743_systick.i

# target to preprocess a source file
drivers/tielve_stm32h743_systick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_systick.c.i
.PHONY : drivers/tielve_stm32h743_systick.c.i

drivers/tielve_stm32h743_systick.s: drivers/tielve_stm32h743_systick.c.s
.PHONY : drivers/tielve_stm32h743_systick.s

# target to generate assembly for a file
drivers/tielve_stm32h743_systick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/drivers/tielve_stm32h743_systick.c.s
.PHONY : drivers/tielve_stm32h743_systick.c.s

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/main.c.s
.PHONY : main.c.s

startup_stm32h743xx.obj: startup_stm32h743xx.s.obj
.PHONY : startup_stm32h743xx.obj

# target to build an object file
startup_stm32h743xx.s.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32h743_baremetal.elf.dir/build.make CMakeFiles/stm32h743_baremetal.elf.dir/startup_stm32h743xx.s.obj
.PHONY : startup_stm32h743xx.s.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flash"
	@echo "... stm32h743_baremetal.elf"
	@echo "... drivers/tielve_stm32h743_gpio.obj"
	@echo "... drivers/tielve_stm32h743_gpio.i"
	@echo "... drivers/tielve_stm32h743_gpio.s"
	@echo "... drivers/tielve_stm32h743_spi.obj"
	@echo "... drivers/tielve_stm32h743_spi.i"
	@echo "... drivers/tielve_stm32h743_spi.s"
	@echo "... drivers/tielve_stm32h743_systick.obj"
	@echo "... drivers/tielve_stm32h743_systick.i"
	@echo "... drivers/tielve_stm32h743_systick.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... startup_stm32h743xx.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

